-- Atomic quotation/invoice save with line replacement
-- Privileged logic lives in private schema; service_role-only INVOKER wrapper in public.
-- See scripts/fix-remaining-linter-warnings.sql for the current implementation.